site_name: Awesome Developer Portfolio
repo_url: https://github.com/smaranjitghose/awesome-portfolio-websites

nav:
    - Home: index.md
    - Getting Started: gs.md
    - Hosting: hosting.md
    - Team: team.md
    - How to Contribute?: Contribution.md

theme:
    name: 'material'
    logo: 'images/icons/logo.png'
    favicon: 'images/icons/logo.png'
    palette:
        scheme: slate
        primary: deep purple
    font:
        text: Poppins
    features:
        - navigation.expand
        - searcn.highlight

plugins:
  - search

google_analytics:
  - UA-XXXXXXXX-X
  - auto

markdown_extensions:
  - attr_list